package com.gist.mathis.model.entity.membership;

public enum MathisPositionHeldEnum {
	SIMPLE_MEMBER,
	PRESIDENT,
	BOARD_MEMBER,
	GENERAL_DIRECTOR,
	AUDITOR,
	MEMBER_OF_THE_CONTROLLING_BODY,
	LEGAL_REPRESENTATIVE,
	ADMINISTRATOR,
	MEMBER_OF_TECHNICAL_COMMITTEE,
	MEMBER_OF_COMMISSION,
	MEMBER_OF_WORKING_GROUP
}
